config/routes.rb
Tzitter::Application.routes.draw do
  resources :zombies

  match '/signup', :to => 'zombies#new'
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'

  root :to => 'pages#home'

end

app/models/zombie.rb
# == Schema Information
# Schema version: 20101206133050
#
# Table name: zombies
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  username   :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

require 'digest'
class Zombie < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :username, :email, :password, :password_confirmation

  @email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, :presence => true,
                   :length => { :maximum => 50 }
  validates :username, :presence => true,
                       :length => { :within => 8..16 },
                       :uniqueness => { :case_sensitive => false }
  validates :email, :presence => true,
                    :format => { :with => @email_regex },
                    :uniqueness => { :case_sensitive => false }

  # Automatically creates the virtual attribute 'password_confirmation'.
  validates :password, :presence => true,
            :confirmation => true,
            :length => { :within => 6..40 }
  
  before_save :encrypt_password

  # Return true if the user's password matches the submitted password.
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate_by_username(username, submitted_password)
    zombie = find_by_username(username)
    return nil  if zombie.nil?
    return zombie if zombie.has_password?(submitted_password)
  end
  
  def self.authenticate_by_email(email, submitted_password)
    zombie = find_by_email(email)
    return nil  if zombie.nil?
    return zombie if zombie.has_password?(submitted_password)
  end

  def self.authenticate(username_email, submitted_password)
    if username_email =~ @email_regex
      email = username_email
      authenticate_by_email(email, submitted_password)
    else
      username = username_email
      authenticate_by_username(username, submitted_password)
    end
  end

  private

    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  $base_title = "Twitter for Zombies"  

  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end

  def about
    @title = "About"
  end

  def help
    @title = "Help"
  end
end

app/controllers/zombies_controller.rb
class ZombiesController < ApplicationController

  def show
    @zombie = Zombie.find(params[:id])
    @title = @zombie.name
  end

  def new
    @title = "Sign up"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # Return a title on a per-page basis.
  def title
    base_title = $base_title
    if @title.nil?
      base_title
    else
      "#{base_title} :: #{@title}"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/zombies_helper.rb
module ZombiesHelper

  def gravatar_for(zombie, options = { :size => 50 })
    gravatar_image_tag(zombie.email.downcase, :alt => zombie.name,
                                              :class => 'gravatar',
                                              :gravatar => options)
  end
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/" target="_blank">News</a></li>
      <li><a href="http://www.railstutorial.org/" target="_blank">Rails Tutorial</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
        <% logo = image_tag("rails_for_zombies_front.jpg", :alt => "#{$base_title}: Brought to you by a Rails for Zombies 'Zombie'", :class => "round") %>
        <%= link_to logo, root_path %>
        <nav class="round">
          <ul>
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Help", help_path %></li>
            <li><%= link_to "Sign in", '#' %></li>
          </ul>
        </nav>
      </header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.min.js" %>
    <%= javascript_include_tag 'rails' %>
    <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
    <%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
    <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
    <%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
    <h1>About <%= $base_title %></h1>
    <p>
      To learn more about &quot;<%= $base_title %>&quot;, go to <a href="http://railsforzombies.org/" target="_blank">Rails for Zombies by EnvyLabs</a>.
    </p>
    <p>
      Of course, this entire application is based off the tutorials from the
      <a href="http://railstutorial.org/" target="_blank">Ruby on Rails Tutorial</a> by Michael Hartl.
    </p>

app/views/pages/contact.html.erb
    <h1>Contact</h1>
    <p>
      To learn more about &quot;<%= $base_title %>&quot;, go to <a href="http://railsforzombies.org/" target="_blank">Rails for Zombies by EnvyLabs</a>.
    </p>
    <p>
      Of course, this entire application is based off the tutorials from the
      <a href="http://railstutorial.org/" target="_blank">Ruby on Rails Tutorial</a> by Michael Hartl.
    </p>

app/views/pages/help.html.erb
<h1>Help</h1>
<p>
  Get help on Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help" target="_blank">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book" target="_blank">Rails Tutorial book</a>.
</p>

app/views/pages/home.html.erb
    <h1><%= $base_title %></h1>
    <p>
      Welcome to <%= $base_title %>! To learn more about &quot;<%= $base_title %>&quot;, go to <a href="http://railsforzombies.org/" target="_blank">Rails for Zombies by EnvyLabs</a>.
    </p>
    <p>
      Of course, this entire application is based off the tutorials from the
      <a href="http://railstutorial.org/" target="_blank">Ruby on Rails Tutorial</a> by Michael Hartl.
    </p>

    <%= link_to "Sign up to create some Zombie Tweets!", signup_path, :class => "signup_button round" %>

app/views/zombies/new.html.erb
<h1>Zombies#new</h1>
<p>Find me in app/views/zombies/new.html.erb</p>

app/views/zombies/show.html.erb
<table class="profile" summary="Profile information">
  <tr>
    <td class="main">
      <h1>
        <%= gravatar_for @zombie %>
        <%= @zombie.name %>
      </h1>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @zombie.name %><br />
      <strong>URL</strong>  <%= link_to zombies_path(@zombie), @zombie %>
    </td>
  </tr>
</table>